INSERT INTO specialties (id, name, slug, active, deleted)
VALUES
  ('specialty-ansiedade', 'Ansiedade', 'ansiedade', true, false),
  ('specialty-ansiedade-generalizada-tag', 'Ansiedade Generalizada (TAG)', 'ansiedade-generalizada-tag', true, false),
  ('specialty-sindrome-do-panico', 'Síndrome do Pânico', 'sindrome-do-panico', true, false),
  ('specialty-fobias', 'Fobias', 'fobias', true, false),
  ('specialty-toc', 'TOC', 'toc', true, false),
  ('specialty-estresse', 'Estresse', 'estresse', true, false),
  ('specialty-tept-transtorno-de-estresse-pos-traumatico', 'TEPT (Transtorno de Estresse Pós-Traumático)', 'tept-transtorno-de-estresse-pos-traumatico', true, false),
  ('specialty-depressao', 'Depressão', 'depressao', true, false),
  ('specialty-transtorno-bipolar', 'Transtorno Bipolar', 'transtorno-bipolar', true, false),
  ('specialty-burnout', 'Burnout', 'burnout', true, false),
  ('specialty-tristeza-persistente', 'Tristeza Persistente', 'tristeza-persistente', true, false),
  ('specialty-esquizofrenia', 'Esquizofrenia', 'esquizofrenia', true, false),
  ('specialty-transtornos-de-humor', 'Transtornos de Humor', 'transtornos-de-humor', true, false),
  ('specialty-relacionamentos', 'Relacionamentos', 'relacionamentos', true, false),
  ('specialty-relacionamento-abusivo', 'Relacionamento Abusivo', 'relacionamento-abusivo', true, false),
  ('specialty-conflitos-amorosos', 'Conflitos Amorosos', 'conflitos-amorosos', true, false),
  ('specialty-conflitos-familiares', 'Conflitos Familiares', 'conflitos-familiares', true, false),
  ('specialty-casamento', 'Casamento', 'casamento', true, false),
  ('specialty-divorcio', 'Separação e Divórcio', 'divorcio', true, false),
  ('specialty-dependencia-emocional', 'Dependência Emocional', 'dependencia-emocional', true, false),
  ('specialty-ciumes', 'Ciúmes', 'ciumes', true, false),
  ('specialty-autoestima', 'Autoestima', 'autoestima', true, false),
  ('specialty-autoconhecimento', 'Autoconhecimento', 'autoconhecimento', true, false),
  ('specialty-inteligencia-emocional', 'Inteligência Emocional', 'inteligencia-emocional', true, false),
  ('specialty-desenvolvimento-pessoal', 'Desenvolvimento Pessoal', 'desenvolvimento-pessoal', true, false),
  ('specialty-projeto-de-vida', 'Projeto de Vida', 'projeto-de-vida', true, false),
  ('specialty-proposito', 'Propósito', 'proposito', true, false),
  ('specialty-motivacao', 'Motivação', 'motivacao', true, false),
  ('specialty-autoconfianca', 'Autoconfiança', 'autoconfianca', true, false),
  ('specialty-carreira', 'Carreira', 'carreira', true, false),
  ('specialty-transicao-de-carreira', 'Transição de Carreira', 'transicao-de-carreira', true, false),
  ('specialty-produtividade', 'Produtividade', 'produtividade', true, false),
  ('specialty-lideranca', 'Liderança', 'lideranca', true, false),
  ('specialty-ambiente-corporativo', 'Ambiente Corporativo', 'ambiente-corporativo', true, false),
  ('specialty-tdah', 'TDAH', 'tdah', true, false),
  ('specialty-autismo-tea', 'TEA (Autismo)', 'autismo-tea', true, false),
  ('specialty-altas-habilidades', 'Altas Habilidades', 'altas-habilidades', true, false),
  ('specialty-dislexia', 'Dislexia', 'dislexia', true, false),
  ('specialty-dificuldades-de-aprendizagem', 'Dificuldades de Aprendizagem', 'dificuldades-de-aprendizagem', true, false),
  ('specialty-psicologia-infantil', 'Psicologia Infantil', 'psicologia-infantil', true, false),
  ('specialty-adolescencia', 'Adolescência', 'adolescencia', true, false),
  ('specialty-desenvolvimento-infantil', 'Desenvolvimento Infantil', 'desenvolvimento-infantil', true, false),
  ('specialty-orientacao-parental', 'Orientação Parental', 'orientacao-parental', true, false),
  ('specialty-bullying', 'Bullying', 'bullying', true, false),
  ('specialty-dificuldades-escolares', 'Dificuldades Escolares', 'dificuldades-escolares', true, false),
  ('specialty-sexualidade', 'Sexualidade', 'sexualidade', true, false),
  ('specialty-identidade-genero', 'Identidade de Gênero', 'identidade-genero', true, false),
  ('specialty-lgbtqia', 'LGBTQIA+', 'lgbtqia', true, false),
  ('specialty-sexologia', 'Sexologia', 'sexologia', true, false),
  ('specialty-disfuncoes-sexuais', 'Disfunções Sexuais', 'disfuncoes-sexuais', true, false),
  ('specialty-transtornos-alimentares', 'Transtornos Alimentares', 'transtornos-alimentares', true, false),
  ('specialty-anorexia', 'Anorexia', 'anorexia', true, false),
  ('specialty-bulimia', 'Bulimia', 'bulimia', true, false),
  ('specialty-compulsao-alimentar', 'Compulsão Alimentar', 'compulsao-alimentar', true, false),
  ('specialty-obesidade', 'Obesidade', 'obesidade', true, false),
  ('specialty-imagem-corporal', 'Imagem Corporal', 'imagem-corporal', true, false),
  ('specialty-dependencia-quimica', 'Dependência Química', 'dependencia-quimica', true, false),
  ('specialty-dependencia-tecnologica', 'Dependência Tecnológica', 'dependencia-tecnologica', true, false),
  ('specialty-jogos-e-games', 'Jogos e Games', 'jogos-e-games', true, false),
  ('specialty-compras-compulsivas', 'Compras Compulsivas', 'compras-compulsivas', true, false),
  ('specialty-vicios', 'Vícios', 'vicios', true, false),
  ('specialty-luto', 'Luto', 'luto', true, false),
  ('specialty-mudancas-de-vida', 'Mudanças de Vida', 'mudancas-de-vida', true, false),
  ('specialty-menopausa', 'Menopausa', 'menopausa', true, false),
  ('specialty-aposentadoria', 'Aposentadoria', 'aposentadoria', true, false),
  ('specialty-saude-da-mulher', 'Saúde da Mulher', 'saude-da-mulher', true, false),
  ('specialty-gestacao', 'Gestação', 'gestacao', true, false),
  ('specialty-puerperio', 'Puerpério', 'puerperio', true, false),
  ('specialty-maternidade', 'Maternidade', 'maternidade', true, false),
  ('specialty-saude-mental-materna', 'Saúde Mental Materna', 'saude-mental-materna', true, false),
  ('specialty-pre-natal-psicologico', 'Pré-natal Psicológico', 'pre-natal-psicologico', true, false),
  ('specialty-doencas-cronicas', 'Doenças Crônicas', 'doencas-cronicas', true, false),
  ('specialty-cancer', 'Câncer', 'cancer', true, false),
  ('specialty-dor-cronica', 'Dor Crônica', 'dor-cronica', true, false),
  ('specialty-cuidados-paliativos', 'Cuidados Paliativos', 'cuidados-paliativos', true, false),
  ('specialty-psicologia-hospitalar', 'Psicologia Hospitalar', 'psicologia-hospitalar', true, false),
  ('specialty-violencia-domestica', 'Violência Doméstica', 'violencia-domestica', true, false),
  ('specialty-violencia-de-genero', 'Violência de Gênero', 'violencia-de-genero', true, false),
  ('specialty-violencia-sexual', 'Violência Sexual', 'violencia-sexual', true, false),
  ('specialty-racismo', 'Racismo', 'racismo', true, false),
  ('specialty-discriminacao', 'Discriminação', 'discriminacao', true, false),
  ('specialty-preconceito', 'Preconceito', 'preconceito', true, false),
  ('specialty-comunicacao', 'Comunicação', 'comunicacao', true, false),
  ('specialty-emocoes', 'Emoções', 'emocoes', true, false),
  ('specialty-sentimentos', 'Sentimentos', 'sentimentos', true, false),
  ('specialty-comportamento', 'Comportamento', 'comportamento', true, false),
  ('specialty-saude-mental', 'Saúde Mental', 'saude-mental', true, false)
ON CONFLICT (slug)
DO UPDATE
SET
  name = EXCLUDED.name,
  active = EXCLUDED.active,
  deleted = EXCLUDED.deleted,
  updated_at = NOW();

UPDATE specialties
SET
  active = false,
  updated_at = NOW()
WHERE deleted = false
  AND slug NOT IN (
    SELECT slug
    FROM (
      VALUES
      ('ansiedade'),
      ('ansiedade-generalizada-tag'),
      ('sindrome-do-panico'),
      ('fobias'),
      ('toc'),
      ('estresse'),
      ('tept-transtorno-de-estresse-pos-traumatico'),
      ('depressao'),
      ('transtorno-bipolar'),
      ('burnout'),
      ('tristeza-persistente'),
      ('esquizofrenia'),
      ('transtornos-de-humor'),
      ('relacionamentos'),
      ('relacionamento-abusivo'),
      ('conflitos-amorosos'),
      ('conflitos-familiares'),
      ('casamento'),
      ('divorcio'),
      ('dependencia-emocional'),
      ('ciumes'),
      ('autoestima'),
      ('autoconhecimento'),
      ('inteligencia-emocional'),
      ('desenvolvimento-pessoal'),
      ('projeto-de-vida'),
      ('proposito'),
      ('motivacao'),
      ('autoconfianca'),
      ('carreira'),
      ('transicao-de-carreira'),
      ('produtividade'),
      ('lideranca'),
      ('ambiente-corporativo'),
      ('tdah'),
      ('autismo-tea'),
      ('altas-habilidades'),
      ('dislexia'),
      ('dificuldades-de-aprendizagem'),
      ('psicologia-infantil'),
      ('adolescencia'),
      ('desenvolvimento-infantil'),
      ('orientacao-parental'),
      ('bullying'),
      ('dificuldades-escolares'),
      ('sexualidade'),
      ('identidade-genero'),
      ('lgbtqia'),
      ('sexologia'),
      ('disfuncoes-sexuais'),
      ('transtornos-alimentares'),
      ('anorexia'),
      ('bulimia'),
      ('compulsao-alimentar'),
      ('obesidade'),
      ('imagem-corporal'),
      ('dependencia-quimica'),
      ('dependencia-tecnologica'),
      ('jogos-e-games'),
      ('compras-compulsivas'),
      ('vicios'),
      ('luto'),
      ('mudancas-de-vida'),
      ('menopausa'),
      ('aposentadoria'),
      ('saude-da-mulher'),
      ('gestacao'),
      ('puerperio'),
      ('maternidade'),
      ('saude-mental-materna'),
      ('pre-natal-psicologico'),
      ('doencas-cronicas'),
      ('cancer'),
      ('dor-cronica'),
      ('cuidados-paliativos'),
      ('psicologia-hospitalar'),
      ('violencia-domestica'),
      ('violencia-de-genero'),
      ('violencia-sexual'),
      ('racismo'),
      ('discriminacao'),
      ('preconceito'),
      ('comunicacao'),
      ('emocoes'),
      ('sentimentos'),
      ('comportamento'),
      ('saude-mental')
    ) AS current_specialty_catalog(slug)
  );
