// WARNING: THIS file is auto-generated.
// Do not edit this file manually.

//Lib
import { Router } from "express";

const middleware = Router();

//Middlewares

import _auth from "../middlewares/_auth";

middleware.use(_auth);

export default middleware;
