import type { AdminPsychologistStatisticsDTO } from "../../DTOs/IAdminPsychologistEngagementDTO";
import {
  ACTIVITY_ACTIONS_SOURCE,
  metric,
  PATIENT_POST_REPLY_COVERAGE_SOURCE,
  PROFILE_VISIBILITY_DETAILED_SOURCE,
  PROFILE_VISIBILITY_TEMPORAL_SOURCE,
} from "./business-content";
import type { AdminPsychologistStatisticsContext } from "./statistics-context";
import { buildVideo } from "./video";
import { buildComparison } from "./visibility-series";

export const buildAdminPsychologistStatisticsResponse = (
  context: AdminPsychologistStatisticsContext,
): AdminPsychologistStatisticsDTO => {
  const {
    activityActions,
    businessProfileConversion,
    businessSeries,
    businessVisibilityDiagnosis,
    commentsReceived,
    communityContentDistribution,
    communityContentSeconds,
    communityEngagementDiagnosis,
    communityItems,
    communityPosts,
    communityReplies,
    communitySeries,
    communityVisibilitySeconds,
    contentViewsCount,
    coverageRate,
    currentPresentationVideoSessions,
    detailedVisibilitySeconds,
    downvotesCount,
    favorites,
    patientPostTextReplyCoverageCount,
    patientPostVideoReplyCoverageCount,
    period,
    platformUsage,
    presentationVideoSeconds,
    previousActivityActions,
    previousCommentsReceived,
    previousCommunityContentSeconds,
    previousCommunityPosts,
    previousCommunityReplies,
    previousCommunityVisibilitySeconds,
    previousCoverageRate,
    previousDownvotesCount,
    previousFavorites,
    previousPatientPostTextReplyCoverageCount,
    previousPatientPostVideoReplyCoverageCount,
    previousPresentationVideoSeconds,
    previousProfileViews,
    previousProfileVisibilitySeconds,
    previousReviews,
    previousSavesCount,
    previousSearchResults,
    previousSharesCount,
    previousUpvotesCount,
    previousVideoActionEvents,
    previousVideoSessions,
    previousVisibilitySeconds,
    previousWhatsappClicks,
    profile,
    profileViews,
    profileVisibilitySeconds,
    reviews,
    savesCount,
    searchResults,
    sharesCount,
    trafficQuality,
    trafficSources,
    unavailable,
    upvotesCount,
    videoActionEvents,
    videoSessions,
    visibilityBreakdownSeries,
    visibilitySeconds,
    whatsappClicks,
  } = context;

  const response: AdminPsychologistStatisticsDTO = {
    business: {
      cards: [
        metric({
          comparison: buildComparison(
            profileViews.length,
            previousProfileViews.length,
            period.period,
          ),
          id: "profile_views",
          label: "Visualizações de perfil",
          source: "profile_view_event.source=profile_page",
          value: profileViews.length,
        }),
        metric({
          comparison: buildComparison(visibilitySeconds, previousVisibilitySeconds, period.period),
          id: "visibility_signal",
          label: "Visibilidade (tempo)",
          source: PROFILE_VISIBILITY_TEMPORAL_SOURCE,
          unit: "seconds",
          value: visibilitySeconds,
        }),
        metric({
          comparison: buildComparison(
            whatsappClicks.length,
            previousWhatsappClicks.length,
            period.period,
          ),
          id: "whatsapp_clicks",
          label: "Cliques no WhatsApp",
          source: "contact_request.channel=whatsapp",
          value: whatsappClicks.length,
        }),
        metric({
          comparison: buildComparison(activityActions, previousActivityActions, period.period),
          id: "activity_score",
          label: "Atividade (ações)",
          source: ACTIVITY_ACTIONS_SOURCE,
          value: activityActions,
        }),
        metric({
          comparison: buildComparison(favorites.length, previousFavorites.length, period.period),
          id: "favorites",
          label: "Favoritados",
          source: "psychologist_favorite",
          value: favorites.length,
        }),
        metric({
          comparison: buildComparison(reviews.length, previousReviews.length, period.period),
          id: "reviews",
          label: "Avaliações",
          source: "professional_review",
          value: reviews.length,
        }),
        metric({
          comparison: buildComparison(
            searchResults.length,
            previousSearchResults.length,
            period.period,
          ),
          id: "search_results",
          label: "Resultados de busca",
          source: "profile_view_event.source=search_result",
          value: searchResults.length,
        }),
      ],
      series: businessSeries,
      profile_conversion: businessProfileConversion,
      visibility: {
        cards: [
          metric({
            comparison: buildComparison(
              profileVisibilitySeconds,
              previousProfileVisibilitySeconds,
              period.period,
            ),
            id: "profile",
            label: "Perfil",
            source: "page_view_event.page_kind=psychologist_profile.duration_seconds",
            unit: "seconds",
            value: profileVisibilitySeconds,
          }),
          metric({
            comparison: buildComparison(
              presentationVideoSeconds,
              previousPresentationVideoSeconds,
              period.period,
            ),
            id: "presentation_video",
            label: "Vídeo de apresentação",
            source: "profile_video_watch_session.watched_seconds",
            unit: "seconds",
            value: presentationVideoSeconds,
          }),
          metric({
            comparison: buildComparison(
              communityContentSeconds,
              previousCommunityContentSeconds,
              period.period,
            ),
            id: "community_content",
            label: "Conteúdo na comunidade",
            source: "content_attention_session.attention_seconds",
            unit: "seconds",
            value: communityContentSeconds,
          }),
        ],
        counters: [
          {
            id: "presentation_video_explore_views",
            label: "Views do vídeo de apresentação no explorar",
            source: "profile_video_watch_session",
            value: currentPresentationVideoSessions.length,
          },
          {
            id: "search_result_views",
            label: "Views do vídeo de apresentação nos resultados de busca",
            source: "profile_view_event.source=search_result",
            value: searchResults.length,
          },
          {
            id: "profile_opens",
            label: "Aberturas do perfil",
            source: "profile_view_event.source=profile_page",
            value: profileViews.length,
          },
          {
            id: "content_views",
            label: "Visualizações de conteúdo na comunidade",
            source: "page_view_event.target_type=post|reply",
            value: contentViewsCount,
          },
        ],
        diagnosis: businessVisibilityDiagnosis,
        series: visibilityBreakdownSeries,
        source: PROFILE_VISIBILITY_DETAILED_SOURCE,
        total_seconds: detailedVisibilitySeconds,
      },
    },
    community: {
      cards: [
        metric({
          comparison: buildComparison(
            communityVisibilitySeconds,
            previousCommunityVisibilitySeconds,
            period.period,
          ),
          id: "community_visibility",
          label: "Visibilidade",
          source: "content_attention_session.attention_seconds",
          unit: "seconds",
          value: communityVisibilitySeconds,
        }),
        metric({
          comparison: buildComparison(
            communityPosts.length,
            previousCommunityPosts.length,
            period.period,
          ),
          id: "posts",
          label: "Posts",
          source: "community_post.author_id",
          value: communityPosts.length,
        }),
        metric({
          comparison: buildComparison(
            communityReplies.length,
            previousCommunityReplies.length,
            period.period,
          ),
          id: "replies",
          label: "Respostas",
          source: "post_reply.author_id",
          value: communityReplies.length,
        }),
        metric({
          available: coverageRate !== null,
          comparison:
            coverageRate !== null
              ? buildComparison(coverageRate, previousCoverageRate ?? 0, period.period)
              : null,
          id: "coverage_rate",
          label: "Taxa de cobertura",
          source: "community_post.author.role=paciente+post_reply.author_id",
          unit: "percentage",
          unavailable_reason:
            coverageRate !== null
              ? null
              : "Nenhum post de paciente foi encontrado no período selecionado.",
          value: coverageRate,
        }),
        metric({
          comparison: buildComparison(
            patientPostTextReplyCoverageCount,
            previousPatientPostTextReplyCoverageCount,
            period.period,
          ),
          id: "patient_post_text_reply_coverage",
          label: "Posts de pacientes respondidos sem vídeo",
          source: PATIENT_POST_REPLY_COVERAGE_SOURCE,
          value: patientPostTextReplyCoverageCount,
        }),
        metric({
          comparison: buildComparison(
            patientPostVideoReplyCoverageCount,
            previousPatientPostVideoReplyCoverageCount,
            period.period,
          ),
          id: "patient_post_video_reply_coverage",
          label: "Posts de pacientes respondidos com vídeo",
          source: PATIENT_POST_REPLY_COVERAGE_SOURCE,
          value: patientPostVideoReplyCoverageCount,
        }),
        metric({
          comparison: buildComparison(upvotesCount, previousUpvotesCount, period.period),
          id: "upvotes",
          label: "Upvotes",
          source: "post_vote.value=1 em community_post/post_reply do psicólogo",
          value: upvotesCount,
        }),
        metric({
          comparison: buildComparison(downvotesCount, previousDownvotesCount, period.period),
          id: "downvotes",
          label: "Downvotes",
          source: "post_vote.value=-1 em community_post/post_reply do psicólogo",
          value: downvotesCount,
        }),
        metric({
          comparison: buildComparison(savesCount, previousSavesCount, period.period),
          id: "saves",
          label: "Salvamentos",
          source: "post_save+post_reply_save",
          value: savesCount,
        }),
        metric({
          comparison: buildComparison(sharesCount, previousSharesCount, period.period),
          id: "shares",
          label: "Compartilhamentos",
          source: "post_share em community_post/post_reply do psicólogo",
          value: sharesCount,
        }),
        metric({
          comparison: buildComparison(
            commentsReceived.length,
            previousCommentsReceived.length,
            period.period,
          ),
          id: "comments_received",
          label: "Comentários recebidos",
          source: "post_reply em posts do psicólogo",
          value: commentsReceived.length,
        }),
      ],
      communities: communityItems,
      content_distribution: communityContentDistribution,
      engagement_diagnosis: communityEngagementDiagnosis,
      series: communitySeries,
    },
    period: period.period,
    platform_usage: platformUsage,
    source:
      "profile_events+community_activity+video_sessions+search_impressions+professional_review+page_view_event+important_action_event+content_attention_session",
    traffic_quality: trafficQuality,
    traffic_sources: trafficSources,
    unavailable,
    video: buildVideo(
      profile,
      videoSessions,
      previousVideoSessions,
      videoActionEvents,
      previousVideoActionEvents,
      searchResults,
      previousSearchResults,
      period.period,
    ),
  };

  return response;
};
