//Repository

//Types
import type { Resolve } from "@/helpers/return";
import { error, msg } from "@/helpers/translate";
//Interfaces
import type { user } from "@/interfaces/objects";
//
import { confirmEmailSend } from "@/modules/api/config/nodemailer/messages/confirm";
import { isTransactionalEmailConfigured } from "@/modules/api/config/nodemailer/send";
import { code } from "@/utils/code";
import { LoginRepository } from "../../../../public/auth/login/repositories/LoginRepository";
import { ConfirmRepository } from "../repositories/ConfirmRepository";

export default async (data: { auth: user }): Promise<Resolve> => {
  const _LOGIN = new LoginRepository();
  const _CONFIRM = new ConfirmRepository();

  const find = await _LOGIN.findByEmail({ b: { email: data.auth.email! } });
  if (!find)
    return {
      status: 404,
      ...error("auth_incorrect", {
        //If you need a custom text
      }),
    };
  if (find.confirmed)
    return {
      status: 400,
      ...error("confirmed_already", {
        //If you need a custom text
      }),
    };

  if (!isTransactionalEmailConfigured()) {
    return {
      status: 503,
      ...error("email_provider_unavailable", {}),
    };
  }

  // WARNING: Replace all '/' generated by the hash function
  const confirm_code = code();

  await _CONFIRM.confirmCode({
    ...find,
    confirm_code,
    confirm_date: new Date(),
  });

  //
  if (find.email) {
    const sent = await confirmEmailSend({
      email: find.email!,
      name: find.name!,
      code: confirm_code,
    });
    if (!sent) {
      return {
        status: 503,
        ...error("email_provider_unavailable", {}),
      };
    }
  }

  return {
    status: 200,
    ...msg("confirm_code_success", {
      //If you need a custom text
    }),
    data: true,
  };
};
