export type CountryCallingCodeOption = {
  country: string;
  label: string;
  value: string;
};

export const COUNTRY_CALLING_CODE_OPTIONS = [
  { country: "AF", label: "Afeganistão (+93)", value: "93" },
  { country: "ZA", label: "África do Sul (+27)", value: "27" },
  { country: "AL", label: "Albânia (+355)", value: "355" },
  { country: "DE", label: "Alemanha (+49)", value: "49" },
  { country: "AD", label: "Andorra (+376)", value: "376" },
  { country: "AO", label: "Angola (+244)", value: "244" },
  { country: "AI", label: "Anguila (+1)", value: "1" },
  { country: "AG", label: "Antígua e Barbuda (+1)", value: "1" },
  { country: "SA", label: "Arábia Saudita (+966)", value: "966" },
  { country: "DZ", label: "Argélia (+213)", value: "213" },
  { country: "AR", label: "Argentina (+54)", value: "54" },
  { country: "AM", label: "Armênia (+374)", value: "374" },
  { country: "AW", label: "Aruba (+297)", value: "297" },
  { country: "AU", label: "Austrália (+61)", value: "61" },
  { country: "AT", label: "Áustria (+43)", value: "43" },
  { country: "AZ", label: "Azerbaijão (+994)", value: "994" },
  { country: "BS", label: "Bahamas (+1)", value: "1" },
  { country: "BD", label: "Bangladesh (+880)", value: "880" },
  { country: "BB", label: "Barbados (+1)", value: "1" },
  { country: "BH", label: "Barein (+973)", value: "973" },
  { country: "BE", label: "Bélgica (+32)", value: "32" },
  { country: "BZ", label: "Belize (+501)", value: "501" },
  { country: "BJ", label: "Benin (+229)", value: "229" },
  { country: "BM", label: "Bermudas (+1)", value: "1" },
  { country: "BY", label: "Bielorrússia (+375)", value: "375" },
  { country: "BO", label: "Bolívia (+591)", value: "591" },
  { country: "BA", label: "Bósnia e Herzegovina (+387)", value: "387" },
  { country: "BW", label: "Botsuana (+267)", value: "267" },
  { country: "BR", label: "Brasil (+55)", value: "55" },
  { country: "BN", label: "Brunei (+673)", value: "673" },
  { country: "BG", label: "Bulgária (+359)", value: "359" },
  { country: "BF", label: "Burquina Faso (+226)", value: "226" },
  { country: "BI", label: "Burundi (+257)", value: "257" },
  { country: "BT", label: "Butão (+975)", value: "975" },
  { country: "CV", label: "Cabo Verde (+238)", value: "238" },
  { country: "CM", label: "Camarões (+237)", value: "237" },
  { country: "KH", label: "Camboja (+855)", value: "855" },
  { country: "CA", label: "Canadá (+1)", value: "1" },
  { country: "QA", label: "Catar (+974)", value: "974" },
  { country: "KZ", label: "Cazaquistão (+7)", value: "7" },
  { country: "TD", label: "Chade (+235)", value: "235" },
  { country: "CL", label: "Chile (+56)", value: "56" },
  { country: "CN", label: "China (+86)", value: "86" },
  { country: "CY", label: "Chipre (+357)", value: "357" },
  { country: "VA", label: "Cidade do Vaticano (+39)", value: "39" },
  { country: "CO", label: "Colômbia (+57)", value: "57" },
  { country: "KM", label: "Comores (+269)", value: "269" },
  { country: "CD", label: "Congo - Kinshasa (+243)", value: "243" },
  { country: "KP", label: "Coreia do Norte (+850)", value: "850" },
  { country: "KR", label: "Coreia do Sul (+82)", value: "82" },
  { country: "CI", label: "Costa do Marfim (+225)", value: "225" },
  { country: "CR", label: "Costa Rica (+506)", value: "506" },
  { country: "HR", label: "Croácia (+385)", value: "385" },
  { country: "CU", label: "Cuba (+53)", value: "53" },
  { country: "CW", label: "Curaçao (+599)", value: "599" },
  { country: "DK", label: "Dinamarca (+45)", value: "45" },
  { country: "DJ", label: "Djibuti (+253)", value: "253" },
  { country: "DM", label: "Dominica (+1)", value: "1" },
  { country: "EG", label: "Egito (+20)", value: "20" },
  { country: "SV", label: "El Salvador (+503)", value: "503" },
  { country: "AE", label: "Emirados Árabes Unidos (+971)", value: "971" },
  { country: "EC", label: "Equador (+593)", value: "593" },
  { country: "ER", label: "Eritreia (+291)", value: "291" },
  { country: "SK", label: "Eslováquia (+421)", value: "421" },
  { country: "SI", label: "Eslovênia (+386)", value: "386" },
  { country: "ES", label: "Espanha (+34)", value: "34" },
  { country: "SZ", label: "Essuatíni (+268)", value: "268" },
  { country: "US", label: "Estados Unidos (+1)", value: "1" },
  { country: "EE", label: "Estônia (+372)", value: "372" },
  { country: "ET", label: "Etiópia (+251)", value: "251" },
  { country: "FJ", label: "Fiji (+679)", value: "679" },
  { country: "PH", label: "Filipinas (+63)", value: "63" },
  { country: "FI", label: "Finlândia (+358)", value: "358" },
  { country: "FR", label: "França (+33)", value: "33" },
  { country: "GA", label: "Gabão (+241)", value: "241" },
  { country: "GM", label: "Gâmbia (+220)", value: "220" },
  { country: "GH", label: "Gana (+233)", value: "233" },
  { country: "GE", label: "Geórgia (+995)", value: "995" },
  { country: "GI", label: "Gibraltar (+350)", value: "350" },
  { country: "GD", label: "Granada (+1)", value: "1" },
  { country: "GR", label: "Grécia (+30)", value: "30" },
  { country: "GL", label: "Groenlândia (+299)", value: "299" },
  { country: "GP", label: "Guadalupe (+590)", value: "590" },
  { country: "GU", label: "Guam (+1)", value: "1" },
  { country: "GT", label: "Guatemala (+502)", value: "502" },
  { country: "GG", label: "Guernsey (+44)", value: "44" },
  { country: "GY", label: "Guiana (+592)", value: "592" },
  { country: "GF", label: "Guiana Francesa (+594)", value: "594" },
  { country: "GN", label: "Guiné (+224)", value: "224" },
  { country: "GQ", label: "Guiné Equatorial (+240)", value: "240" },
  { country: "GW", label: "Guiné-Bissau (+245)", value: "245" },
  { country: "HT", label: "Haiti (+509)", value: "509" },
  { country: "HN", label: "Honduras (+504)", value: "504" },
  { country: "HK", label: "Hong Kong, RAE da China (+852)", value: "852" },
  { country: "HU", label: "Hungria (+36)", value: "36" },
  { country: "YE", label: "Iêmen (+967)", value: "967" },
  { country: "CX", label: "Ilha Christmas (+61)", value: "61" },
  { country: "AC", label: "Ilha de Ascensão (+247)", value: "247" },
  { country: "IM", label: "Ilha de Man (+44)", value: "44" },
  { country: "NF", label: "Ilha Norfolk (+672)", value: "672" },
  { country: "AX", label: "Ilhas Aland (+358)", value: "358" },
  { country: "KY", label: "Ilhas Cayman (+1)", value: "1" },
  { country: "CC", label: "Ilhas Cocos (Keeling) (+61)", value: "61" },
  { country: "CK", label: "Ilhas Cook (+682)", value: "682" },
  { country: "FO", label: "Ilhas Faroé (+298)", value: "298" },
  { country: "FK", label: "Ilhas Malvinas (+500)", value: "500" },
  { country: "MP", label: "Ilhas Marianas do Norte (+1)", value: "1" },
  { country: "MH", label: "Ilhas Marshall (+692)", value: "692" },
  { country: "SB", label: "Ilhas Salomão (+677)", value: "677" },
  { country: "TC", label: "Ilhas Turcas e Caicos (+1)", value: "1" },
  { country: "VI", label: "Ilhas Virgens Americanas (+1)", value: "1" },
  { country: "VG", label: "Ilhas Virgens Britânicas (+1)", value: "1" },
  { country: "IN", label: "Índia (+91)", value: "91" },
  { country: "ID", label: "Indonésia (+62)", value: "62" },
  { country: "IR", label: "Irã (+98)", value: "98" },
  { country: "IQ", label: "Iraque (+964)", value: "964" },
  { country: "IE", label: "Irlanda (+353)", value: "353" },
  { country: "IS", label: "Islândia (+354)", value: "354" },
  { country: "IL", label: "Israel (+972)", value: "972" },
  { country: "IT", label: "Itália (+39)", value: "39" },
  { country: "JM", label: "Jamaica (+1)", value: "1" },
  { country: "JP", label: "Japão (+81)", value: "81" },
  { country: "JE", label: "Jersey (+44)", value: "44" },
  { country: "JO", label: "Jordânia (+962)", value: "962" },
  { country: "XK", label: "Kosovo (+383)", value: "383" },
  { country: "KW", label: "Kuwait (+965)", value: "965" },
  { country: "LA", label: "Laos (+856)", value: "856" },
  { country: "LS", label: "Lesoto (+266)", value: "266" },
  { country: "LV", label: "Letônia (+371)", value: "371" },
  { country: "LB", label: "Líbano (+961)", value: "961" },
  { country: "LR", label: "Libéria (+231)", value: "231" },
  { country: "LY", label: "Líbia (+218)", value: "218" },
  { country: "LI", label: "Liechtenstein (+423)", value: "423" },
  { country: "LT", label: "Lituânia (+370)", value: "370" },
  { country: "LU", label: "Luxemburgo (+352)", value: "352" },
  { country: "MO", label: "Macau, RAE da China (+853)", value: "853" },
  { country: "MK", label: "Macedônia do Norte (+389)", value: "389" },
  { country: "MG", label: "Madagascar (+261)", value: "261" },
  { country: "MY", label: "Malásia (+60)", value: "60" },
  { country: "MW", label: "Malaui (+265)", value: "265" },
  { country: "MV", label: "Maldivas (+960)", value: "960" },
  { country: "ML", label: "Mali (+223)", value: "223" },
  { country: "MT", label: "Malta (+356)", value: "356" },
  { country: "MA", label: "Marrocos (+212)", value: "212" },
  { country: "MQ", label: "Martinica (+596)", value: "596" },
  { country: "MU", label: "Maurício (+230)", value: "230" },
  { country: "MR", label: "Mauritânia (+222)", value: "222" },
  { country: "YT", label: "Mayotte (+262)", value: "262" },
  { country: "MX", label: "México (+52)", value: "52" },
  { country: "MM", label: "Mianmar (Birmânia) (+95)", value: "95" },
  { country: "FM", label: "Micronésia (+691)", value: "691" },
  { country: "MZ", label: "Moçambique (+258)", value: "258" },
  { country: "MD", label: "Moldávia (+373)", value: "373" },
  { country: "MC", label: "Mônaco (+377)", value: "377" },
  { country: "MN", label: "Mongólia (+976)", value: "976" },
  { country: "ME", label: "Montenegro (+382)", value: "382" },
  { country: "MS", label: "Montserrat (+1)", value: "1" },
  { country: "NA", label: "Namíbia (+264)", value: "264" },
  { country: "NR", label: "Nauru (+674)", value: "674" },
  { country: "NP", label: "Nepal (+977)", value: "977" },
  { country: "NI", label: "Nicarágua (+505)", value: "505" },
  { country: "NE", label: "Níger (+227)", value: "227" },
  { country: "NG", label: "Nigéria (+234)", value: "234" },
  { country: "NU", label: "Niue (+683)", value: "683" },
  { country: "NO", label: "Noruega (+47)", value: "47" },
  { country: "NC", label: "Nova Caledônia (+687)", value: "687" },
  { country: "NZ", label: "Nova Zelândia (+64)", value: "64" },
  { country: "OM", label: "Omã (+968)", value: "968" },
  { country: "NL", label: "Países Baixos (+31)", value: "31" },
  { country: "BQ", label: "Países Baixos Caribenhos (+599)", value: "599" },
  { country: "PW", label: "Palau (+680)", value: "680" },
  { country: "PA", label: "Panamá (+507)", value: "507" },
  { country: "PG", label: "Papua-Nova Guiné (+675)", value: "675" },
  { country: "PK", label: "Paquistão (+92)", value: "92" },
  { country: "PY", label: "Paraguai (+595)", value: "595" },
  { country: "PE", label: "Peru (+51)", value: "51" },
  { country: "PF", label: "Polinésia Francesa (+689)", value: "689" },
  { country: "PL", label: "Polônia (+48)", value: "48" },
  { country: "PR", label: "Porto Rico (+1)", value: "1" },
  { country: "PT", label: "Portugal (+351)", value: "351" },
  { country: "KE", label: "Quênia (+254)", value: "254" },
  { country: "KG", label: "Quirguistão (+996)", value: "996" },
  { country: "KI", label: "Quiribati (+686)", value: "686" },
  { country: "GB", label: "Reino Unido (+44)", value: "44" },
  { country: "CF", label: "República Centro-Africana (+236)", value: "236" },
  { country: "CG", label: "República do Congo (+242)", value: "242" },
  { country: "DO", label: "República Dominicana (+1)", value: "1" },
  { country: "RE", label: "Reunião (+262)", value: "262" },
  { country: "RO", label: "Romênia (+40)", value: "40" },
  { country: "RW", label: "Ruanda (+250)", value: "250" },
  { country: "RU", label: "Rússia (+7)", value: "7" },
  { country: "EH", label: "Saara Ocidental (+212)", value: "212" },
  { country: "WS", label: "Samoa (+685)", value: "685" },
  { country: "AS", label: "Samoa Americana (+1)", value: "1" },
  { country: "SM", label: "San Marino (+378)", value: "378" },
  { country: "SH", label: "Santa Helena (+290)", value: "290" },
  { country: "LC", label: "Santa Lúcia (+1)", value: "1" },
  { country: "BL", label: "São Bartolomeu (+590)", value: "590" },
  { country: "KN", label: "São Cristóvão e Névis (+1)", value: "1" },
  { country: "MF", label: "São Martinho (+590)", value: "590" },
  { country: "PM", label: "São Pedro e Miquelão (+508)", value: "508" },
  { country: "ST", label: "São Tomé e Príncipe (+239)", value: "239" },
  { country: "VC", label: "São Vicente e Granadinas (+1)", value: "1" },
  { country: "SC", label: "Seicheles (+248)", value: "248" },
  { country: "SN", label: "Senegal (+221)", value: "221" },
  { country: "SL", label: "Serra Leoa (+232)", value: "232" },
  { country: "RS", label: "Sérvia (+381)", value: "381" },
  { country: "SG", label: "Singapura (+65)", value: "65" },
  { country: "SX", label: "Sint Maarten (+1)", value: "1" },
  { country: "SY", label: "Síria (+963)", value: "963" },
  { country: "SO", label: "Somália (+252)", value: "252" },
  { country: "LK", label: "Sri Lanka (+94)", value: "94" },
  { country: "SD", label: "Sudão (+249)", value: "249" },
  { country: "SS", label: "Sudão do Sul (+211)", value: "211" },
  { country: "SE", label: "Suécia (+46)", value: "46" },
  { country: "CH", label: "Suíça (+41)", value: "41" },
  { country: "SR", label: "Suriname (+597)", value: "597" },
  { country: "SJ", label: "Svalbard e Jan Mayen (+47)", value: "47" },
  { country: "TJ", label: "Tadjiquistão (+992)", value: "992" },
  { country: "TH", label: "Tailândia (+66)", value: "66" },
  { country: "TW", label: "Taiwan (+886)", value: "886" },
  { country: "TZ", label: "Tanzânia (+255)", value: "255" },
  { country: "CZ", label: "Tchéquia (+420)", value: "420" },
  { country: "IO", label: "Território Britânico do Oceano Índico (+246)", value: "246" },
  { country: "PS", label: "Territórios palestinos (+970)", value: "970" },
  { country: "TL", label: "Timor-Leste (+670)", value: "670" },
  { country: "TG", label: "Togo (+228)", value: "228" },
  { country: "TK", label: "Tokelau (+690)", value: "690" },
  { country: "TO", label: "Tonga (+676)", value: "676" },
  { country: "TT", label: "Trinidad e Tobago (+1)", value: "1" },
  { country: "TA", label: "Tristão da Cunha (+290)", value: "290" },
  { country: "TN", label: "Tunísia (+216)", value: "216" },
  { country: "TM", label: "Turcomenistão (+993)", value: "993" },
  { country: "TR", label: "Turquia (+90)", value: "90" },
  { country: "TV", label: "Tuvalu (+688)", value: "688" },
  { country: "UA", label: "Ucrânia (+380)", value: "380" },
  { country: "UG", label: "Uganda (+256)", value: "256" },
  { country: "UY", label: "Uruguai (+598)", value: "598" },
  { country: "UZ", label: "Uzbequistão (+998)", value: "998" },
  { country: "VU", label: "Vanuatu (+678)", value: "678" },
  { country: "VE", label: "Venezuela (+58)", value: "58" },
  { country: "VN", label: "Vietnã (+84)", value: "84" },
  { country: "WF", label: "Wallis e Futuna (+681)", value: "681" },
  { country: "ZM", label: "Zâmbia (+260)", value: "260" },
  { country: "ZW", label: "Zimbábue (+263)", value: "263" },
] satisfies CountryCallingCodeOption[];

export const DEFAULT_COUNTRY_CALLING_CODE = "55";

export const findCountryCallingCode = (phone?: string | null) => {
  const digits = (phone || "").replace(/\D/g, "");

  if (!digits) return DEFAULT_COUNTRY_CALLING_CODE;

  const candidates = COUNTRY_CALLING_CODE_OPTIONS.map((option) => option.value).sort(
    (a, b) => b.length - a.length,
  );

  return candidates.find((code) => digits.startsWith(code)) || DEFAULT_COUNTRY_CALLING_CODE;
};
